name: habito_meter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_slidable: ^3.0.0 
  eva_icons_flutter: ^3.1.0 
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_heatmap_calendar: ^1.0.5
  lottie: ^2.6.0
  slide_to_act: ^2.0.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.0
  video_player: ^2.7.0

flutter_native_splash:
  color: "#000000"
  animations: habito_meter\animations\finalLogo.json
  
fonts:
  - family: Gotham
    fonts: 
      - assets: habito_meter\assets\fonts\GothamMedium.ttf
      - assets: habito_meter\assets\fonts\GothamBold.ttf
      - assets: habito_meter\assets\fonts\GothamBook.ttf


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  
  
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/HabitoLogo.png"
  
  
  
flutter: 
  uses-material-design: true
  assets:
    - animations/
  